version: "3.7"
services:
    whatsapp-api:
      image: rafaellessa/whatsapp-api:${DOCKER_IMAGE_TAG:-latest}
      build:
        context: ./whatsapp-api
        dockerfile: Dockerfile
      volumes:
          - /app/node_modules/
          - ./whatsapp-api/code:/app
      ports:
          - "${WHATSAPP_API_PORT:-3001}:${WHATSAPP_API_PORT:-3001}"
          - "9230:9229"
      command: npx prisma migrate dev
      logging:
          driver: "json-file"
          options:
              max-file: "2"
              max-size: "10m"
      environment:

          DATABASE_URL: mysql://${MYSQL_DB_USERNAME}:${MYSQL_DB_PASSWORD}@${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/${MYSQL_DB_DATABASE}"

          #Mysql
          MYSQL_DB_HOST: service-mysql
          MYSQL_DB_PORT: 3306
          MYSQL_DB_USERNAME: ${MYSQL_DB_USERNAME}
          MYSQL_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
          MYSQL_DB_DATABASE: ${MYSQL_DB_DATABASE}

          # Redis
          REDIS_HOST: service-redis
          REDIS_PORT: 6379
          REDIS_CACHE_DB: 0
          REDIS_DB: 0
          REDIS_PREFIX: "CacheChat:"
          CACHE_PREFIX: "Chat:"

          # Ambiente do node
          WHATSAPP_API_ENV: ${WHATSAPP_API_ENV}
          WHATSAPP_API_PORT: ${WHATSAPP_API_PORT}

          JWT_SECRET: ${JWT_SECRET}

      networks:
          - whatsapp-network

      restart: unless-stopped
      
    service-redis:
      image: redis
      container_name: smtp-redis
      networks:
        - whatsapp-network

      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "10m"

      restart: always
    
    service-mysql:
      image: mysql:5.7
      ports:
          - "3306:3306"
      networks:
          - whatsapp-network
      container_name: service-mysql
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DB_DATABASE}

      logging:
          driver: "json-file"
          options:
              max-file: "2"
              max-size: "10m"

      restart: always

networks:
    whatsapp-network:
        external: true